spring:
  application:
    name: configserver
  profiles:
    active:native
  cloud :
    config:
      server:
        native:
          search-locations: file:///C:/Users/Amal/Desktop/microservices/config-server/src/main/resources/config


