spring:
  application:
    name: configserver
  profiles:
    active:native
  cloud :
    config:
      server:
        native:
          search-locations: C:\Users\ASUS\OneDrive\Bureau\spring\ecomerce\configserver\src\main\resources\config

